### ISSUE TITLE
Roadmap v0.1

### ISSUE THREAD

**Issue by malkoG** [kodingwarrior/memedex-backend#1]
# Purpose

FastAPI 학습 목적으로 시작하는 프로젝트인 만큼, 간단하게 이미지를 업로드할 수 있는 API 서버를 만드는 것을 목표로 한다.

```[tasklist]
### API
- [ ] https://github.com/kodingwarrior/memedex-backend/issues/2
- [ ] https://github.com/kodingwarrior/memedex-backend/issues/3
- [ ] https://github.com/kodingwarrior/memedex-backend/issues/4
```

```[tasklist]
### 툴링
- [ ] https://github.com/kodingwarrior/memedex-backend/issues/5
- [ ] https://github.com/kodingwarrior/memedex-backend/issues/6
- [ ] https://github.com/kodingwarrior/memedex-backend/issues/7
```
